### ISSUE TITLE
snippy error

### ISSUE THREAD

**Issue by springerbrowne** [tseemann/nullarbor#138]
Hi,

I seem to have run into an issue with snippy in the pipeline.  I double checked the reference files (all have data) in response to a similar closed issue.

My only explanation is an error in file path it is using (one folder off?):

From the snps log:
Error reading file '/media/springer/evo/Output/03139_France_human/03139_France_human/reference/./ref/genes.gff'

The actual path to that file on my computer:
'/media/springer/evo/Output/03139_France_human/03139_France_human/reference/ref/genes.gff.gz'

I have attached the full command line output and snps.log as well.

I'll keep at it in the meantime (I'm new to this)...thank you for the help,
Springer
[Commandlineoutput_SNPerror.txt](https://github.com/tseemann/nullarbor/files/1599027/Commandlineoutput_SNPerror.txt)
[snps.log](https://github.com/tseemann/nullarbor/files/1599028/snps.log)

Command line output:
[12:15:00] Running: snpEff build -c reference/snpeff.config -dataDir . -gff3 ref 2>> snps.log
[12:15:02] Error running command, check 02113_France_human/02113_France_human/snps.log
Makefile:31: recipe for target '02113_France_human/02113_France_human/snps.tab' failed
make: *** [02113_France_human/02113_France_human/snps.tab] Error 2
make: *** Waiting for unfinished jobs....
[12:15:03] Error running command, check 03139_France_human/03139_France_human/snps.log
Makefile:83: recipe for target '03139_France_human/03139_France_human/snps.tab' failed
make: *** [03139_France_human/03139_France_human/snps.tab] Error 2
make: Leaving directory '/media/springer/evo/Output'

snps.log output:
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error reading file '/media/springer/evo/Output/03139_France_human/03139_France_human/reference/./ref/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Offending line (lineNum: 107): 'NC_013361	snippy	repeat_region	113265	114566	.	+	0	'. File '/media/springer/evo/Output/03139_France_human/03139_France_human/reference/./ref/genes.gff' line 107
	'NC_013361	snippy	repeat_region	113265	114566	.	+	0	'

	at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:353)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:118)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:362)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)

**Comment by springerbrowne** [comment]
I have the same error with just running Snippy 3.2 alone on one set of paired reads....  I'll move the post over to snippy.
Apologies!
springer

**Comment by springerbrowne** [comment]
I couldn't figure out what was the source of the error (suspect snpEff?).

I ran:
brew switch snippy 3.1

And now it is back to purring along.  I did a new brew install of Nullarbor less than a week ago and it looks like the snippy 3.2-var might have an oddity?  Just a heads up.
springer
